### ISSUE TITLE
Runtime Error regarding the project

### ISSUE THREAD

**Issue by mmichaelzhang** [samihaija/mixhop#2]
Hi,

I encountered this issue when trying to run the code with Mac OS 10.15.1:

python ngcn_trainer.py --adj_pows=0,1,2,3 --retrain --l2reg=1e-3 --dataset_name=ind.cora --learn_rate=1 --early_stop_steps=200 --output_layer=fc --hidden_dim=10 --replication_factor=3
Traceback (most recent call last):
  File "ngcn_trainer.py", line 317, in <module>
    app.run(main)
  File "/Library/Python/2.7/site-packages/absl/app.py", line 274, in run
    _run_main(main, args)
  File "/Library/Python/2.7/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "ngcn_trainer.py", line 176, in main
    replica=r, pass_kernel_regularizer=True)
  File "/Users/michael/Research/Startup_Predict/baseline/mixhop-master/mixhop_model.py", line 155, in add_layer
    fn(self.activations[-1], *args, **kwargs))
  File "/Users/michael/Research/Startup_Predict/baseline/mixhop-master/mixhop_model.py", line 160, in mixhop_layer
    kernel_regularizer, layer_id, replica)
  File "/Users/michael/Research/Startup_Predict/baseline/mixhop-master/mixhop_model.py", line 63, in mixhop_layer
    net_p = layer.apply(net_p)
  File "/Library/Python/2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 774, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/tensorflow/python/layers/base.py", line 329, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 696, in __call__
    self.build(input_shapes)
  File "/Library/Python/2.7/site-packages/tensorflow/python/keras/layers/core.py", line 881, in build
    raise ValueError('The last dimension of the inputs to `Dense` '
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

I am using python 2.7.16 and my tensorflow version is 
tensorflow             2.0.0     
tensorflow-estimator   2.0.1     

I also tried using python3.5.4 to run the code but the error is different but like this:

python3 ngcn_trainer.py --adj_pows=0,1,2,3 --retrain --l2reg=1e-3 --dataset_name=ind.cora --learn_rate=1 --early_stop_steps=200 --output_layer=fc --hidden_dim=10 --replication_factor=3
Traceback (most recent call last):
  File "ngcn_trainer.py", line 13, in <module>
    import tensorflow.contrib.slim as slim
ImportError: No module named 'tensorflow.contrib'

I was trying with the ngcn model and the cora dataset, but I think the issue is similar to other datasets and the MixHop model.

Could you please provide the settings of your build?

**Comment by ShengGuanWSU** [comment]
@mmichaelzhang have you solved this issue by any chance?
